name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish
    strategy:
      matrix:
        arch: [aarch64, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Add-on
        uses: home-assistant/builder@2025.11.0
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data \
            --tag  ${{ github.event.release.tag_name || 'latest' }} \
            --image "${{ github.repository_owner }}/hassio-tado-local-{arch}" \
            --docker-hub ghcr.io